apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-j8xp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-j8xp
    app.kubernetes.io/part-of: tkrw-pr712-0075-0048-app
  name: devfile-sample-j8xp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-j8xp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-j8xp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-j8xp@sha256:9f9e8033ecbf7c94c4d3f95b9f22917b70e9ebf4a70d674ceb1fac3b2fcc8560
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
